

apiVersion:v1
kind:pod
matadata:
  name: result-app-pod
  labels:
    name: result-app-pod
	app: demo-voting-app
	
	
spec:
  containers: 
    name: result-app
	image: dockersamples/examplesvotingapp_result
	ports:
	  containerPort: 80